//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal_Ecommerce.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Productos
    {
        [Required]
        public int id { get; set; }

        [Required]
        [Display(Name = "Nombre*")]
        [StringLength(30, ErrorMessage = "El número de caracteres de {0} debe ser al menos {2}.", MinimumLength = 6)]
        public string nombre { get; set; }
        [Required]
        [Display(Name = "Descripción*")]
        [StringLength(30, ErrorMessage = "El número de caracteres de {0} debe ser al menos {2}.", MinimumLength = 6)]
        public string descripcion { get; set; }
        
        public int id_categoria { get; set; }

        [Required]
        [Display(Name = "Cantidad*")]
        public int cantidad { get; set; }

        [Required]
        [Display(Name = "Proveedor*")]
        public int id_proveedor { get; set; }

        [Required]
        [Display(Name = "Precio de compra*")]
        public decimal precio_compra { get; set; }

        [Required]
        [Display(Name = "Precio de venta*")]
        public decimal precio_venta { get; set; }

        [Required]
        [Display(Name = "Stock*")]
        public int stock { get; set; }

        [Required]
        public int stat { get; set; }
        public string img { get; set; }
        public Nullable<decimal> calificacion { get; set; }
    }
}
