//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal_Ecommerce.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Proveedores
    {

        [Required]
        public int id { get; set; }
        [Required]
        [Display(Name = "Razon Social*")]
        [StringLength(50, ErrorMessage = "El número de caracteres de {0} debe ser al menos {2}.", MinimumLength = 6)]
        public string razon_social { get; set; }
        [Required]
        [Display(Name = "RFC*")]
        [StringLength(15, ErrorMessage = "El número de caracteres de {0} debe ser al menos {2}.", MinimumLength = 13)]
        public string rfc { get; set; }
        [Required]
        [Display(Name = "Dirección*")]
        [StringLength(50, ErrorMessage = "El número de caracteres de {0} debe ser al menos {2}.", MinimumLength = 6)]
        public string direccion { get; set; }
        [Required]
        [Display(Name = "Teléfono*")]
        [StringLength(13, ErrorMessage = "El número de caracteres de {0} debe ser al menos {2}.", MinimumLength = 10)]
        public string telefono { get; set; }
        [Required]
        [EmailAddress]
        [Display(Name = "Correo*")]
        [StringLength(30, ErrorMessage = "El número de caracteres de {0} debe ser al menos {2}.", MinimumLength = 10)]
        public string correo { get; set; }
        [Required]
        public int stat { get; set; }
    }
}
